
# GL02_A23_TAJH


Application de gestion et de préparation de tests et examens en ligne, se basant sur des fichiers au format link:https://docs.moodle.org/2x/fr/Format_GIFT[GIFT].

## Pré-requis

Vous devez au préalable installer **Node.js version 14.21.3**, ou plus.

## Installation

Avant de lancer l'application, vous devez installer les dépendances en effectuant la commande suivante  dans le répertoire GL02_A23_TAJH.

----
npm install
----

## Lancement

Importer les fichiers GIFT que vous voulez utiliser dans le dossier data/gift.

Pour lancer l'application, rester dans le même dossier et lancer la commande suivante :
----
node main.js
----

## Licence
MIT License

Copyright (c) 2023 Pandoison

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

## Contributeurs

- BRISSET timo
- MAZEAU Antoine
- CZERNIAK Hugo
- RAOULT Juliette
- HENNECHART Louis
- CHEMLAL Nassim
- ZIYI Huang
- CHENGXIAN Zhao
- CHEYNET Maël
